<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SantoshSrinivas-15MBP-0401.local" ignored="0" name="/Users/santoshsrinivas/Documents/restassured" tests="10" failures="1" timestamp="2020-05-10T10:50:35 IST" time="11.085" errors="0">
  <testcase name="registrationSuccessfulAPI" time="2.684" classname="com.restassured.TC001_POST_Request">
    <failure type="java.lang.AssertionError" message="expected [OPERATION_SUCCESS] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [OPERATION_SUCCESS] but found [null]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEqualsImpl(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.restassured.TC001_POST_Request.registrationSuccessfulAPI(TC001_POST_Request.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- registrationSuccessfulAPI -->
  <testcase name="googleMapTest" time="0.525" classname="com.restassured.TC003_GET_Request"/>
  <testcase name="getWeatherDetails" time="0.449" classname="com.restassured.TC004_GET_Request"/>
  <testcase name="validateResponse" time="0.716" classname="com.restassured.TC005_GET_Request"/>
  <testcase name="getResponse" time="0.799" classname="com.restassured.TC006_GET_Request"/>
  <testcase name="userAuth" time="0.653" classname="com.restassured.TC007_GET_Request"/>
  <testcase name="addNewEmp" time="1.491" classname="datadriventesting.DataDriven_AddEmp"/>
  <testcase name="addNewEmp" time="0.861" classname="datadriventesting.DataDriven_AddEmp"/>
  <testcase name="addNewEmp" time="0.877" classname="datadriventesting.DataDriven_AddEmp"/>
  <testcase name="addNewEmp" time="0.912" classname="datadriventesting.DataDriven_AddEmp"/>
</testsuite> <!-- /Users/santoshsrinivas/Documents/restassured -->
